DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS lists;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL, 
    password VARCHAR(255) NOT NULL
);


CREATE TABLE lists(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    owner_id INTEGER NOT NULL, 
    list TEXT,
    FOREIGN KEY(owner_id) REFERENCES users (id)
);